id: IC5AC9940
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T13:53:43+00:00'
last_modified: '2022-06-07T15:22:48.899068+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD181171
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས། མགོན་ཁང་གསོལ་ཀའི་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D120:
      image_group_id: I1KG16336
      title: ''
      total_pages: 1046
      order: 1
      base_file: D120.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
