id: P001850
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD181171
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས། མགོན་ཁང་གསོལ་ཀའི་སྐོར།
  author: ''
  volumes:
    327f4a19fe3f46a7b8ebca96a1b67948:
      image_group_id: I1KG16336
      title: ''
      volume_number: 1
      total_pages: 1046
