id: P001850
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-17 10:25:52.404055
source_metadata:
  id: bdr:W1PD181171
  title: སྔ་འགྱུར་གཡག་ཟེ་དགོན་གྱི་འདོན་ཆ་ལས། མགོན་ཁང་གསོལ་ཀའི་སྐོར།
  author: ''
  volumes:
    327f4a19fe3f46a7b8ebca96a1b67948:
      image_group_id: I1KG16336
      title: ''
      volume_number: 1
      total_pages: 1046
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
